on:
  pull_request:
    branches: master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v3
      # run the container, attaching this repo as a working directory
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: rocker/verse:4.3.1
          shell: bash
          run: |
            # execute from the repo
            cd /home/rstudio/mwe/

            # run pre-render scripts
            r render-pdf.r